### ISSUE TITLE
vimrc not found

### ISSUE THREAD

**Issue by xuannianc** [rapphil/vim-python-ide#1]
Fantastic.Thank you for the sharing.  https://github.com/rapphil/vim-python-ide/blob/master/install.sh#L18 There's no vimrc in the repo.

**Comment by rapphil** [comment]
Sorry, I'm going to fix that. Thanks for checking that out and taking the time to comment!

**Comment by rapphil** [comment]
Fixed! @xuannianc  fell free to test and close this issue! Thanks again.

**Comment by xuannianc** [comment]
Aha, thanks. I thought there would be some basic settings like 'expandtab' in it.

**Comment by rapphil** [comment]
The indentation is handled by the vim-polyglot plugin which uses vim-python-indent plugin under the hood https://github.com/Vimjas/vim-python-pep8-indent . That is why we don't need a expandtab. 

Also, in the end of the installation, you can customize your .vimrc, that will be generated automatically in your home folder.
